### ISSUE TITLE
Problems when dealing with black-and-white pictures

### ISSUE THREAD

**Issue by Uylee** [Kalafinaian/python-img_gist_feature#2]
Hi, if there is a black-and-white pictures in the datasets there will be a little problems, so, I add some codes in 'utils_gist.py' to fit the data. If you feel necessary you can add it in the source codes for future use ^.^

![image](https://user-images.githubusercontent.com/46954265/82542559-cb7a4e00-9b84-11ea-9e70-4652a7c51828.png)

**Comment by Uylee** [comment]
Perhaps there are some redundancy codes but it works, you can deal with it in your way if necessary. Wish you a good day!

**Comment by Yumeka999** [comment]
ok, good idea!
